import { Role, User } from "@xwmtp/bingo-tournament";

export const entrantsResponse: User[] = [
  {
    id: "vrZyM4orbEoqDJX0",
    name: "Fenyan",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/Ava.png",
    twitchChannel: "https://www.twitch.tv/fenyan",
  },
  {
    id: "jQbq4dBp7yWvlrG0",
    name: "Link11",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/Link-1.png",
    twitchChannel: "https://www.twitch.tv/link__11",
  },
  {
    id: "VXY0eABdn7oLKPnz",
    name: "MatttInTheHat",
    roles: [Role.Entrant, Role.Restreamer],
    twitchChannel: "https://www.twitch.tv/matttinthehat",
  },
  {
    id: "VXY0eABd6boLKPnz",
    name: "shaggy",
    roles: [Role.Entrant],
    twitchChannel: "https://www.twitch.tv/shaggy3311",
  },
  {
    id: "jQbq4dBpey3vlrG0",
    name: "MooseOoT",
    roles: [Role.Entrant],
    twitchChannel: "https://www.twitch.tv/mooseoot",
  },
  {
    id: "XGzr7pBMny3kqgyE",
    name: "juwk",
    roles: [Role.Entrant],
    twitchChannel: "https://www.twitch.tv/juwk",
  },
  {
    id: "kzM65aWXgxo1y8q0",
    name: "Runnerguy2489",
    roles: [Role.Entrant, Role.Restreamer],
    avatar: "https://racetime.gg/media/Runnerguy.png",
    twitchChannel: "https://www.twitch.tv/runnerguy2489",
  },
  {
    id: "wNZ1KRBOV8W4qAyj",
    name: "tob3000",
    roles: [Role.Entrant],
    twitchChannel: "https://www.twitch.tv/tob3000",
  },
  {
    id: "LNY0OkW1OP3KalP1",
    name: "CoffeePot",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/coff.png",
    twitchChannel: "https://www.twitch.tv/coffeepot",
  },
  {
    id: "Va0eMongz6Wl9pyJ",
    name: "2DollarGargoyle",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/poe_triforce_better.png",
    twitchChannel: "https://www.twitch.tv/2dollargargoyle",
  },
  {
    id: "NX5783Jbkl3qlL0a",
    name: "Savestate",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/avatars-000682414328-zt3639-t500x500.jpg",
    twitchChannel: "https://www.twitch.tv/savestate",
  },
  {
    id: "rZyM4orRvRoqDJX0",
    name: "jenslang",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/e0aaf3c8688abd0e58bed9d9f63de4ad.png",
    twitchChannel: "https://www.twitch.tv/jenslang",
  },
  {
    id: "VXY0eABddNBLKPnz",
    name: "shiroaeli",
    roles: [Role.Entrant, Role.Restreamer],
    twitchChannel: "https://www.twitch.tv/shiroaeli",
  },
  {
    id: "wdm1LPWjAoEnVx6k",
    name: "dotzo",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/dotzo_-_black_aO9qZEm.png",
    twitchChannel: "https://www.twitch.tv/dotzo",
  },
  {
    id: "b8GPMWwQvO31nEk0",
    name: "Midboss",
    roles: [Role.Entrant],
    twitchChannel: "https://www.twitch.tv/madbossblinds",
  },
  {
    id: "Ek8wpok94mB5KQyV",
    name: "WickedGligar",
    roles: [Role.Entrant, Role.Restreamer],
    avatar: "https://racetime.gg/media/Gligar.jfif",
    twitchChannel: "https://www.twitch.tv/wickedgligar",
  },
  {
    id: "JXzVwZWqElW5k8eb",
    name: "the__consultant",
    roles: [Role.Entrant, Role.Restreamer],
    avatar: "https://racetime.gg/media/Excel_Face_257.jpg",
    twitchChannel: "https://www.twitch.tv/the__consultant",
  },
  {
    id: "xldAMBl4A4BaOP57",
    name: "Gombill",
    roles: [Role.Entrant],
    twitchChannel: "https://www.twitch.tv/gombill",
  },
  {
    id: "R8QGZrB2k03Ngk4V",
    name: "Challensois_",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/Malon_copy.png",
    twitchChannel: "https://www.twitch.tv/challensois_",
  },
  {
    id: "lYZa5B5pLPW2Vwv9",
    name: "Myelin",
    roles: [Role.Entrant],
    twitchChannel: "https://www.twitch.tv/myelin_sr",
  },
  {
    id: "wezlNoA4443mq6db",
    name: "PaintSkate8",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/drawing_of_me.jpg",
    twitchChannel: "https://www.twitch.tv/paintskate8",
  },
  {
    id: "Ek8wpok9GkB5KQyV",
    name: "neefe",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/ivysquare.png",
    twitchChannel: "https://www.twitch.tv/neefe",
  },
  {
    id: "Ek8wpok9KVB5KQyV",
    name: "Countdown",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/steiner_HD.png",
    twitchChannel: "https://www.twitch.tv/countdown69",
  },
  {
    id: "wdm1LPWjyeoEnVx6",
    name: "Tashman91",
    roles: [Role.Entrant],
    twitchChannel: "https://www.twitch.tv/tashman91",
  },
  {
    id: "rVwLN8B8PPBPa52R",
    name: "JFM2796",
    roles: [Role.Entrant, Role.Restreamer],
    avatar: "https://racetime.gg/media/Screenshot_20200817-035639_YouTube.jpg",
    twitchChannel: "https://www.twitch.tv/jfm2796",
  },
  {
    id: "ZbpNAaBvn5BJkg04",
    name: "Exodus",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/bottleblack.png",
    twitchChannel: "https://www.twitch.tv/exodus122",
  },
  {
    id: "R8QGZrB2q0WNgk4V",
    name: "Cloudike",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/profil_twitch_cloudike_250.png",
    twitchChannel: "https://www.twitch.tv/cloudike",
  },
  {
    id: "LxldAMBlYV3aOP57",
    name: "Timato",
    roles: [Role.Entrant],
    twitchChannel: "https://www.twitch.tv/timato_",
  },
  {
    id: "7lYZa5B5eZB2Vwv9",
    name: "MutantAura",
    roles: [Role.Entrant, Role.Restreamer],
    avatar: "https://racetime.gg/media/5454518169c837a73da4f74202a5960a.webp",
    twitchChannel: "https://www.twitch.tv/mutantaura",
  },
  {
    id: "JN9rVpW9eRWjq8Ll",
    name: "AverageGreg",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/warioBlazed.png",
    twitchChannel: "https://www.twitch.tv/averagegreg",
  },
  {
    id: "Aa5veoGybABMVr6Z",
    name: "triforce3250",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/ZeldaRacetimeThumbnail.jpg",
    twitchChannel: "https://www.twitch.tv/triforce3250",
  },
  {
    id: "Ek8wpokQQ7B5KQyV",
    name: "Apasher",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/nagisa_400x400.jpg",
    twitchChannel: "https://www.twitch.tv/apasher_",
  },
  {
    id: "ZVa0eMonnbol9pyJ",
    name: "adef",
    roles: [Role.Entrant, Role.Restreamer],
    avatar: "https://racetime.gg/media/adef.png",
    twitchChannel: "https://www.twitch.tv/adef",
  },
  {
    id: "52QE8oNlGXBlywqX",
    name: "Grego",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/purplepixel_DXDp79m.png",
    twitchChannel: "https://www.twitch.tv/grego_the_greatest",
  },
  {
    id: "17DexWEQPyWak64R",
    name: "benstephens56",
    roles: [Role.Entrant, Role.Restreamer],
    avatar: "https://racetime.gg/media/long_linkx100.png",
    twitchChannel: "https://www.twitch.tv/benstephens56",
  },
  {
    id: "NX5783JddGWqlL0a",
    name: "moosecrap",
    roles: [Role.Entrant],
    twitchChannel: "https://www.twitch.tv/moosecrap",
  },
  {
    id: "rZyM4orGgqWqDJX0",
    name: "gamestabled",
    roles: [Role.Entrant],
    twitchChannel: "https://www.twitch.tv/gamestabled",
  },
  {
    id: "OR6ym83myb3Pd1Xr",
    name: "Titou",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/france.PNG",
    twitchChannel: "https://www.twitch.tv/p_titou",
  },
  {
    id: "XY0eABdQnX3LKPnz",
    name: "Bou_Frost",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/BouAvatar_640.jpg",
    twitchChannel: "https://www.twitch.tv/bou_frost",
  },
  {
    id: "dm1LPWj2DOWEnVx6",
    name: "Darker",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/UjEwSk6G_400x400.jpg",
    twitchChannel: "https://www.twitch.tv/darkerandroid",
  },
  {
    id: "pRbOXG3yZboZVKq1",
    name: "Cisco64",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/HeroOfTime.png",
    twitchChannel: "https://www.twitch.tv/cisco64",
  },
  {
    id: "57ZKD3g5jGWkyANO",
    name: "Glasfolie",
    roles: [Role.Entrant],
    twitchChannel: "https://www.twitch.tv/glasfolie",
  },
  {
    id: "Gzr7pBMG7YokqgyE",
    name: "khuno",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/Goron_Mask.ico",
    twitchChannel: "https://www.twitch.tv/khuno7",
  },
  {
    id: "LxldAMBlnboaOP57",
    name: "LiterallyLake",
    roles: [Role.Entrant],
    twitchChannel: "https://www.twitch.tv/literallylake",
  },
  {
    id: "jb8GPMWwDLB1nEk0",
    name: "blinkzy",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/reallyhappy.png",
    twitchChannel: "https://www.twitch.tv/yzknilb",
  },
  {
    id: "yMewn83V89W405Jv",
    name: "PsyMarth",
    roles: [Role.Entrant, Role.Restreamer],
    avatar: "https://racetime.gg/media/logo_100px.png",
    twitchChannel: "https://www.twitch.tv/psymarth",
  },
  {
    id: "dm1LPWjZLLWEnVx6",
    name: "Cabbage72",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/20220726_155822.jpg",
    twitchChannel: "https://www.twitch.tv/cabbage72",
  },
  {
    id: "1jgrbWP5Z5Be7P5Q",
    name: "The corpser",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/vibe.gif",
    twitchChannel: "https://www.twitch.tv/thecorpser",
  },
  {
    id: "5rNGD3DKVaB9blOy",
    name: "FantaTanked",
    roles: [Role.Entrant],
    avatar: "https://racetime.gg/media/jimmyW.png",
    twitchChannel: "https://www.twitch.tv/fantatanked",
  },
  {
    id: "kzM65aWX6b31y8q0",
    name: "Nalle",
    roles: [Role.Entrant, Role.Restreamer],
    avatar: "https://racetime.gg/media/gator2gif.gif",
    twitchChannel: "https://www.twitch.tv/nallesounds",
  },
];
